import Joi from 'joi';

export enum EnvEnum {
  PORT = 'PORT',
  SA_PWD = 'SA_PWD',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  ZIP_PASSWORD = 'ZIP_PASSWORD',
  CLOUDMERSIVE_CONVERT_API_KEY = 'CLOUDMERSIVE_CONVERT_API_KEY',
  MAILER_USER = 'MAILER_USER',
  MAILER_PASSWORD = 'MAILER_PASSWORD',
}
